### ISSUE TITLE
Forget ';' in /src/Main/Main.php#L16

### ISSUE THREAD

**Issue by hadiswais** [pH-7/RESTful-API-TDD-book#1]
https://github.com/pH-7/RESTful-API-TDD-book/blob/b2af4ec56a0f30c461c31761903dc102487be8b0/sourcecode/src/Main/Main.php#L16

**Comment by pH-7** [comment]
Good catch @hadiswais! I will fix it.
BTW, do you have any feedback concerning this project? If so, please let me know 😊 I appreciate it.
